[package]
name = "rustx-cli"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.69"
clap = "4.1.8"
serde = { version = "1.0.152", features = ["derive"] }
xshell = "0.2.3"
