[package]
name = "rustx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
byteorder = "1.4.3"
bytes = "1.4.0"
chrono = "0.4.23"
clap = "4.1.8"
crossbeam = "0.8.2"
derive_more = "0.99.17"
env_logger = "0.10.0"
extension-trait = "1.0.1"
futures = "0.3.26"
http = "0.2.9"
hyper = "0.14.24"
log = "0.4.17"
rand = "0.8.5"
rayon = "1.7.0"
reqwest = "0.11.14"
serde = "1.0.152"
serde_json = "1.0.94"
tempfile = "3.4.0"
tera = "1.17.1"
thiserror = "1.0.39"
tokio = "1.26.0"
toml = "0.7.2"
