[package]
name = "rustx"
version = "0.1.0"
edition = "2021"


[features]

default = [
  "rx-profile-std-plus",
]


## ---------- ##


rx-crates-core = [
  "anyhow",
  "backtrace",
  "big_s",
  "blake3",
  "byteorder",
  "bytes",
  "chrono",
  "clap",
  "crossbeam",
  "derive_more",
  "extension-trait",
  "fnv",
  "futures",
]


## ---------- ##


rx-profile-no-std = [
  "rx-rustlibs-core",
  "rx-crates-core",
]

rx-profile-std-plus = [
  "rx-rustlibs-std",
  "rx-crates-core",
  "rx-feature-std",
  "rx-feature-default",
]

rx-profile-net = [
  "rx-profile-std-plus",
  "http",
  "hyper",
  "hyper/full",
]

rx-profile-cli = [
  "rx-profile-std-plus",
  "env_logger",
]

rx-profile-async = [
  "rx-profile-std-plus",
]

rx-profile-build-script = [
  "rx-profile-std-plus",
  "cc",
  "cxx",
]

rx-profile-full = [
  "rx-profile-cli",
  "rx-profile-async",
  "rx-profile-build-script",
]


## ---------- ##

rx-feature-std = [  
  "anyhow/std",
  "backtrace/std",
  "blake3/std",
  "byteorder/std",
  "bytes/std",
  "chrono/std",
  "clap/std",
  "crossbeam/std",
  "cxx/std",
  "fnv/std",
  "futures/std",
]

rx-feature-default = [
  "chrono/default",
  "clap/default",
  "futures/default",
]

rx-feature-serde = [
  "backtrace/serde",
  "bytes/serde",
]

rx-feature-backtrace = [
  "rx-feature-std",
  "anyhow/backtrace",
]

rx-feature-tokio = [
]

rx-feature-nightly = [
]


## ---------- ##


rx-rustlibs-core = [
  "rx-rustlib-core",
  "rx-rustlib-alloc",
]

rx-rustlibs-std = [
  "rx-rustlib-core",
  "rx-rustlib-alloc",
  "rx-rustlib-std",
  "rx-rustlib-proc_macro",
]

rx-rustlib-core = []
rx-rustlib-alloc = []
rx-rustlib-std = []
rx-rustlib-proc_macro = []


[dependencies]
anyhow = { version = "1.0.69", optional = true, default-features = false }
backtrace = {version = "0.3.67", optional = true, default-features = false }
big_s = { version = "1.0.2", optional = true, default-features = false }
blake3 = { version = "1.3.3", optional = true, default-features = false }
byteorder = {version = "1.4.3", optional = true, default-features = false }
bytes = { version = "1.4.0", optional = true, default-features = false }
cc = { version = "1.0.79", optional = true, default-features = false }
chrono = { version = "0.4.23", optional = true, default-features = false }
clap = { version = "4.1.8", optional = true, default-features = false }
crossbeam = { version = "0.8.2", optional = true, default-features = false }
cxx = { version = "1.0.92", optional = true, default-features = false }
derive_more = { version = "0.99.17", optional = true, default-features = false }
env_logger = { version = "0.10.0", optional = true, default-features = false }
extension-trait = { version = "1.0.1", optional = true, default-features = false }
fnv = { version = "1.0.7", optional = true, default-features = false }
futures = { version = "0.3.26", optional = true, default-features = false }
http = { version = "0.2.9", optional = true, default-features = false }
hyper = { version = "0.14.24", optional = true, default-features = false }
itertools = "0.10.5"
json5 = "0.4.1"
lazy_static = "1.4.0"
log = "0.4.17"
num_enum = "0.5.11"
og_fmt = "1.0.4"
once_cell = "1.17.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_pcg = "0.3.1"
rayon = "1.7.0"
regex = "1.7.1"
reqwest = "0.11.14"
serde = "1.0.152"
serde_json = "1.0.94"
socket2 = "0.5.1"
static_assertions = "1.1.0"
tempfile = "3.4.0"
tera = "1.17.1"
thiserror = "1.0.39"
tokio = "1.26.0"
toml = "0.7.2"
unicode-segmentation = "1.10.1"
xshell = "0.2.3"
