[package]
name = "rustx"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
big_s = "1.0.2"
blake3 = "1.3.3"
byteorder = "1.4.3"
bytes = "1.4.0"
cc = "1.0.79"
chrono = "0.4.23"
clap = "4.1.8"
crossbeam = "0.8.2"
derive_more = "0.99.17"
env_logger = "0.10.0"
extension-trait = "1.0.1"
fs2 = "0.4.3"
futures = "0.3.26"
http = "0.2.9"
hyper = "0.14.24"
json5 = "0.4.1"
log = "0.4.17"
num_enum = "0.5.11"
og_fmt = "1.0.4"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_pcg = "0.3.1"
rayon = "1.7.0"
regex = "1.7.1"
reqwest = "0.11.14"
serde = "1.0.152"
serde_json = "1.0.94"
static_assertions = "1.1.0"
tempfile = "3.4.0"
tera = "1.17.1"
thiserror = "1.0.39"
tokio = "1.26.0"
toml = "0.7.2"
unicode-segmentation = "1.10.1"
xshell = "0.2.3"
