//! Configuration file parsing for `anthology.toml` and `anthology.json5`.

use rmx::prelude::*;
use rmx::semver::{Version, VersionReq};
use std::path::{Path, PathBuf};

use crate::{Error, Result};

/// The version of Anthology reading the config.
///
/// Compared against a collection's `anthology_version` requirement.
pub const ANTHOLOGY_VERSION: &str = env!("CARGO_PKG_VERSION");

/// A config file format Anthology can read.
///
/// TOML is the default and what `init` writes.
/// JSON5 is accepted for collections generated by other tools,
/// since it reads plain JSON as well as its own extensions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConfigFormat {
    Toml,
    Json5,
}

impl ConfigFormat {
    /// The config file name this format is read from.
    pub fn file_name(self) -> &'static str {
        match self {
            ConfigFormat::Toml => "anthology.toml",
            ConfigFormat::Json5 => "anthology.json5",
        }
    }

    /// The formats searched for, in precedence order.
    pub fn search_order() -> [ConfigFormat; 2] {
        [ConfigFormat::Toml, ConfigFormat::Json5]
    }
}

/// Main configuration for a collection.
#[rmx::derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Config {
    #[serde(default)]
    pub collection: CollectionConfig,
    #[serde(default)]
    pub build: BuildConfig,
    #[serde(default)]
    pub content: ContentConfig,
    #[serde(default)]
    pub server: ServerConfig,
    #[serde(default)]
    pub highlight: HighlightConfig,
}

impl Config {
    /// Load configuration from a collection directory.
    ///
    /// Looks for each format in [`ConfigFormat::search_order`]
    /// and parses the first one present.
    pub fn load(root: &Path) -> Result<Self> {
        let Some((path, format)) = Self::find(root) else {
            return Err(Error::CollectionNotFound {
                path: root.to_path_buf(),
            });
        };

        let text = std::fs::read_to_string(&path)?;
        let config = Self::parse(&text, format, &path)?;
        config.check_version(&path)?;
        Ok(config)
    }

    /// Locate a collection's config file and the format it is written in.
    pub fn find(root: &Path) -> Option<(PathBuf, ConfigFormat)> {
        ConfigFormat::search_order()
            .into_iter()
            .map(|format| (root.join(format.file_name()), format))
            .find(|(path, _)| path.exists())
    }

    /// Parse config text in a given format.
    ///
    /// `path` names the source only for error reporting.
    pub fn parse(text: &str, format: ConfigFormat, path: &Path) -> Result<Self> {
        match format {
            ConfigFormat::Toml => rmx::toml::from_str(text).map_err(|e| Error::ConfigParse {
                path: path.to_path_buf(),
                source: e,
            }),
            ConfigFormat::Json5 => {
                rmx::json5::from_str(text).map_err(|e| Error::ConfigParseJson5 {
                    path: path.to_path_buf(),
                    source: e,
                })
            }
        }
    }

    /// Check this build of Anthology against the collection's requirement.
    ///
    /// A collection with no `anthology_version` accepts any version.
    fn check_version(&self, path: &Path) -> Result<()> {
        let Some(req) = &self.collection.anthology_version else {
            return Ok(());
        };

        let req = VersionReq::parse(req).map_err(|e| {
            Error::config(format!(
                "{}: `anthology_version` is not a version requirement: {e}",
                path.display(),
            ))
        })?;

        // The crate version is generated by Cargo, so it always parses.
        let version = Version::parse(ANTHOLOGY_VERSION).expect("crate version is semver");

        if !req.matches(&version) {
            return Err(Error::config(format!(
                "{}: collection requires Anthology {req}, but this is {version}",
                path.display(),
            )));
        }

        Ok(())
    }
}

/// Collection metadata.
#[rmx::derive(Debug, Clone, Serialize, Deserialize)]
pub struct CollectionConfig {
    /// Title of the collection/site.
    #[serde(default = "default_title")]
    pub title: String,
    /// Base URL for the site.
    #[serde(default)]
    pub base_url: String,
    /// Description of the collection.
    #[serde(default)]
    pub description: String,
    /// Author name.
    #[serde(default)]
    pub author: String,
    /// Language code (e.g., "en").
    #[serde(default = "default_language")]
    pub language: String,
    /// Semver requirement on the Anthology version that may build this
    /// collection, checked at load time. Absent means any version.
    #[serde(default)]
    pub anthology_version: Option<String>,
}

impl Default for CollectionConfig {
    fn default() -> Self {
        Self {
            title: default_title(),
            base_url: String::new(),
            description: String::new(),
            author: String::new(),
            language: default_language(),
            anthology_version: None,
        }
    }
}

fn default_title() -> String {
    "My Collection".to_string()
}

fn default_language() -> String {
    "en".to_string()
}

/// Build configuration.
#[rmx::derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuildConfig {
    /// Output directory for built site.
    #[serde(default = "default_output_dir")]
    pub output_dir: String,
    /// Theme directory name.
    #[serde(default = "default_theme")]
    pub theme: String,
    /// Whether to include drafts in builds.
    #[serde(default)]
    pub drafts: bool,
    /// Minify HTML output.
    #[serde(default)]
    pub minify: bool,
    /// Seed for generated identifiers.
    ///
    /// Setting it makes a build reproducible: the same content produces the
    /// same output bytes. Leaving it unset draws from the OS each build.
    #[serde(default)]
    pub seed: Option<u64>,
}

impl Default for BuildConfig {
    fn default() -> Self {
        Self {
            output_dir: default_output_dir(),
            theme: default_theme(),
            drafts: false,
            minify: false,
            seed: None,
        }
    }
}

fn default_output_dir() -> String {
    "output".to_string()
}

fn default_theme() -> String {
    "default".to_string()
}

/// Content configuration.
#[rmx::derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContentConfig {
    /// Date format for parsing and display.
    #[serde(default = "default_date_format")]
    pub date_format: String,
    /// Default template for documents.
    #[serde(default = "default_template")]
    pub default_template: String,
    /// Excerpt separator in content.
    #[serde(default = "default_excerpt_separator")]
    pub excerpt_separator: String,
}

impl Default for ContentConfig {
    fn default() -> Self {
        Self {
            date_format: default_date_format(),
            default_template: default_template(),
            excerpt_separator: default_excerpt_separator(),
        }
    }
}

fn default_date_format() -> String {
    "%Y-%m-%d".to_string()
}

fn default_template() -> String {
    "default.html".to_string()
}

fn default_excerpt_separator() -> String {
    "<!--more-->".to_string()
}

/// Development server configuration.
#[rmx::derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerConfig {
    /// Port to listen on.
    #[serde(default = "default_port")]
    pub port: u16,
    /// Whether to open browser on start.
    #[serde(default)]
    pub open: bool,
}

impl Default for ServerConfig {
    fn default() -> Self {
        Self {
            port: default_port(),
            open: false,
        }
    }
}

fn default_port() -> u16 {
    3000
}

/// Syntax highlighting configuration.
#[rmx::derive(Debug, Clone, Serialize, Deserialize)]
pub struct HighlightConfig {
    /// Enable syntax highlighting for code blocks.
    #[serde(default = "default_highlight_enabled")]
    pub enabled: bool,
    /// Color theme name (github, github-dark, monokai, dracula, one-dark, solarized-light, solarized-dark, nord).
    #[serde(default = "default_highlight_theme")]
    pub theme: String,
    /// Show line numbers in code blocks.
    #[serde(default = "default_line_numbers")]
    pub line_numbers: bool,
    /// Show copy button on code blocks.
    #[serde(default = "default_copy_button")]
    pub copy_button: bool,
}

impl Default for HighlightConfig {
    fn default() -> Self {
        Self {
            enabled: default_highlight_enabled(),
            theme: default_highlight_theme(),
            line_numbers: default_line_numbers(),
            copy_button: default_copy_button(),
        }
    }
}

fn default_highlight_enabled() -> bool {
    true
}

fn default_highlight_theme() -> String {
    "github-dark".to_string()
}

fn default_line_numbers() -> bool {
    true
}

fn default_copy_button() -> bool {
    true
}

impl HighlightConfig {
    /// Convert to HighlightOptions for the highlighter.
    pub fn to_options(&self) -> crate::build::HighlightOptions {
        crate::build::HighlightOptions {
            theme: self.theme.clone(),
            line_numbers: self.line_numbers,
            copy_button: self.copy_button,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rmx::tempfile::tempdir;

    fn write(dir: &Path, name: &str, text: &str) {
        std::fs::write(dir.join(name), text).unwrap();
    }

    #[test]
    fn loads_toml_config() {
        let dir = tempdir().unwrap();
        write(
            dir.path(),
            "anthology.toml",
            r#"
[collection]
title = "Tomlish"
"#,
        );

        let config = Config::load(dir.path()).unwrap();
        assert_eq!(config.collection.title, "Tomlish");
        assert_eq!(config.build.output_dir, "output");
    }

    #[test]
    fn loads_json5_config_with_comments_and_trailing_commas() {
        let dir = tempdir().unwrap();
        write(
            dir.path(),
            "anthology.json5",
            r#"
{
    // JSON5 allows comments and unquoted keys.
    collection: {
        title: "Jsonish",
    },
    server: { port: 8080 },
}
"#,
        );

        let config = Config::load(dir.path()).unwrap();
        assert_eq!(config.collection.title, "Jsonish");
        assert_eq!(config.server.port, 8080);
    }

    #[test]
    fn toml_wins_when_both_formats_are_present() {
        let dir = tempdir().unwrap();
        write(dir.path(), "anthology.toml", "[collection]\ntitle = \"Toml\"\n");
        write(dir.path(), "anthology.json5", "{ collection: { title: 'Json5' } }");

        let config = Config::load(dir.path()).unwrap();
        assert_eq!(config.collection.title, "Toml");
    }

    #[test]
    fn missing_config_reports_the_collection_root() {
        let dir = tempdir().unwrap();
        let err = Config::load(dir.path()).unwrap_err();
        assert!(matches!(err, Error::CollectionNotFound { .. }));
    }

    #[test]
    fn malformed_json5_names_its_file() {
        let dir = tempdir().unwrap();
        write(dir.path(), "anthology.json5", "{ collection: ");

        let err = Config::load(dir.path()).unwrap_err();
        assert!(matches!(err, Error::ConfigParseJson5 { .. }));
        assert!(err.to_string().contains("anthology.json5"));
    }

    #[test]
    fn satisfiable_version_requirement_loads() {
        let dir = tempdir().unwrap();
        write(
            dir.path(),
            "anthology.toml",
            "[collection]\nanthology_version = \"*\"\n",
        );

        assert!(Config::load(dir.path()).is_ok());
    }

    #[test]
    fn unsatisfiable_version_requirement_is_rejected() {
        let dir = tempdir().unwrap();
        write(
            dir.path(),
            "anthology.toml",
            "[collection]\nanthology_version = \">=99.0.0\"\n",
        );

        let err = Config::load(dir.path()).unwrap_err().to_string();
        assert!(err.contains(">=99.0.0"), "{err}");
        assert!(err.contains(ANTHOLOGY_VERSION), "{err}");
    }

    #[test]
    fn nonsense_version_requirement_is_rejected() {
        let dir = tempdir().unwrap();
        write(
            dir.path(),
            "anthology.toml",
            "[collection]\nanthology_version = \"not a version\"\n",
        );

        let err = Config::load(dir.path()).unwrap_err().to_string();
        assert!(err.contains("not a version requirement"), "{err}");
    }

    #[test]
    fn defaults_round_trip_through_both_formats() {
        let config = Config::default();

        let toml = rmx::toml::to_string(&config).unwrap();
        let from_toml = Config::parse(&toml, ConfigFormat::Toml, Path::new("t")).unwrap();
        assert_eq!(from_toml.collection.title, config.collection.title);

        let json = rmx::serde_json::to_string(&config).unwrap();
        let from_json5 = Config::parse(&json, ConfigFormat::Json5, Path::new("j")).unwrap();
        assert_eq!(from_json5.server.port, config.server.port);
    }
}
